config/routes.rb
Rails.application.routes.draw do
  resources :shortened_links
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'shortened_links#new'
  get "/s/:short_url_slug", action: :shortened, controller: 'shortened_links'
  
  scope '/admin' do
    resources :shortened_links, only: [:index, :update]
  end

  resources :shortened_links do
    member do
      patch :toggle_expire_link_status
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortened_link.rb
class ShortenedLink < ApplicationRecord

    validates :original_url, presence: true, on: :create
    validates_format_of :original_url, with: /\A(?:(?:http|https):\/\/)?([-a-zA-Z0-9.]{2,256}\.[a-z]{2,4})\b(?:\/[-a-zA-Z0-9@,!:%_\+.~#?&\/\/=]*)?\z/
    validates_uniqueness_of :short_url_slug
    before_validation :set_default_values, :sanitize_original_url, on: :create

    # Regex:
    # for validates_format_of (http[s] optional)
    # /\A(?:(?:http|https):\/\/)?([-a-zA-Z0-9.]{2,256}\.[a-z]{2,4})\b(?:\/[-a-zA-Z0-9@,!:%_\+.~#?&\/\/=]*)?\z/
    # for http prepend in sanitize_original_url
    # /\Ahttps?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)\z/

    protected
    # Set the default vaules for a new shortened link
    ## short_url_slug to be a 6 digit alpha numeric validated to be unique.
    ## visit_count set to 0, increments after every show
    ## is_expired to be set to true in edit by the end user. if true, filter from index list..
    def set_default_values
        self.short_url_slug     = rand(36**6).to_s(36)
        self.visit_count        = 0
        self.is_expired         = false
        # TODO: Need to retry for random generation of short_url slug, odds are pretty solid for no dups, but just in case it shouldnt fail outright.
    end

    def sanitize_original_url
        self.original_url = self.original_url.prepend('http://') unless /\Ahttps?\:\/\/.+\z/ =~ self.original_url
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  
  def not_found
    raise ActiveRecord::RecordNotFound
  end
  
  private 

  def record_not_found
    render plain: "404 Not Found", status: 404
  end
end

app/controllers/shortened_links_controller.rb
class ShortenedLinksController < ApplicationController
  before_action :set_shortened_link, only: [:show, :edit, :update, :destroy, :toggle_expire_link_status]

  # GET /shortened_links
  # GET /shortened_links.json
  def index
    @shortened_links = ShortenedLink.all
  end

  # GET /shortened_links/1
  # GET /shortened_links/1.json
  def show
  end

  # GET /shortened_links/new
  def new
    @shortened_link = ShortenedLink.new
  end

  # GET /shortened_links/1/edit
  def edit
  end

  # POST /shortened_links
  # POST /shortened_links.json
  def create
    @shortened_link = ShortenedLink.new(shortened_link_params)

    respond_to do |format|
      if @shortened_link.save
        format.html { redirect_to @shortened_link, notice: 'Shortened link was successfully created.' }
        format.json { render :show, status: :created, location: @shortened_link }
      else
        format.html { render :new }
        format.json { render json: @shortened_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shortened_links/1
  # PATCH/PUT /shortened_links/1.json
  def update
    respond_to do |format|
      if @shortened_link.update(shortened_link_params)
        format.html { redirect_to @shortened_link, notice: 'Shortened link was successfully updated.' }
        format.json { render :show, status: :ok, location: @shortened_link }
      else
        format.html { render :edit }
        format.json { render json: @shortened_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shortened_links/1
  # DELETE /shortened_links/1.json
  def destroy
    @shortened_link.destroy
    respond_to do |format|
      format.html { redirect_to shortened_links_url, notice: 'Shortened link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def shortened
    @shortened_link = find_shortend_link or not_found
    unless @shortened_link.is_expired
      increment_visits
      redirect_to @shortened_link.original_url, :status => 301
    else
      not_found
    end
  end

  def toggle_expire_link_status
    @shortened_link.toggle!(:is_expired)
    respond_to do |format|
      format.html { redirect_to shortened_links_url, notice: "#{@shortened_link.short_url_slug} was was updated" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shortened_link
      @shortened_link = ShortenedLink.find(params[:id])
    end

    def find_shortend_link
      @shotened_link = ShortenedLink.find_by_short_url_slug(params[:short_url_slug])
    end

    def increment_visits
      @shortened_link.increment(:visit_count, 1)
      @shortened_link.save
    end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def shortened_link_params
      params.require(:shortened_link).permit(:original_url, :is_expired)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/shortened_links_helper.rb
module ShortenedLinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shrtstck</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">ShrtStck.io</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'All Links', shortened_links_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'New Link', new_shortened_link_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shortened_links/_form.html.erb
<%= form_with(model: shortened_link, local: true) do |form| %>
  <% if shortened_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shortened_link.errors.count, "error") %> prohibited this shortened_link from being saved:</h2>

      <ul>
      <% shortened_link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :original_url %>
    <%= form.text_area :original_url %>
  </div>

  <div class="field">
    <%= form.label :is_expired %>
    <%= form.check_box :is_expired %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shortened_links/edit.html.erb
<div class="container">
  <div class="row">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">Editing Shortened Link</h1>
        <%= form_for @shortened_link do |form| %>
          <% if @shortened_link.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@shortened_link.errors.count, "error") %> prohibited this shortened_link from being saved:</h2>

              <ul>
              <% @shortened_link.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <p>
            <strong>Original URL:</strong>
            <%= @shortened_link.original_url %>
          </p>

          <p>
            <strong>Shortened Link:</strong>
            <%= request.base_url + '/s/' + @shortened_link.short_url_slug %>
          </p>

          <p>
            <strong>Visit Count:</strong>
            <%= @shortened_link.visit_count %>
          </p>

          <div class="field">
            <%= form.label :is_expired %>
            <%= form.check_box :is_expired %>
          </div>

          <div class="actions">
            <%= form.submit :Submit, class:"btn btn-primary"  %>
          </div>
        <% end %>

        <%= link_to 'Show Link', @shortened_link %> |
        <%= link_to 'All Links', shortened_links_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shortened_links/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <div class="row">
    <div class="col-10">
      <h1>Shortened Links</h1>
    </div>
    <div class="col-2">
      <%= link_to 'New Shortened Link', new_shortened_link_path, class:"btn btn-primary" %>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Original Link</th>
        <th>Short Link</th>
        <th>Visits</th>
        <th>Is Expired?</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @shortened_links.each do |shortened_link| %>
        <tr>
          <td><%= shortened_link.original_url %></td>
          <td><%= link_to request.base_url + '/s/' + shortened_link.short_url_slug, '/s/' + shortened_link.short_url_slug %></td>
          <td><%= shortened_link.visit_count %></td>
          <td><%= shortened_link.is_expired %></td>
          <td><%= link_to 'Manage Link', edit_shortened_link_path(shortened_link) %></td>
          <td><%= link_to "#{ shortened_link.is_expired ? 'Activate Link' : 'Expire Link' }", toggle_expire_link_status_shortened_link_path(shortened_link), method: :patch, remote: :true %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/shortened_links/new.html.erb
<div class="container">
  <div class="row">
    <h1>ShrtStack: A Link Shortener</h1>
  </div>
  <%= form_for @shortened_link do |form| %>
    <% if @shortened_link.errors.any? %>
        <% @shortened_link.errors.full_messages.each do |message| %>
          <div class="alert alert-danger" role="alert"> <%= message %> </div>
        <% end %>
    <% end %>
    <div class="form-group">
      <div class="field">
        <%= form.label :original_url %>
        <%= form.text_area :original_url, size: "120x4", class: "form-control" %>
      </div>
    </div>
    <div class="actions">
      <%= form.submit :Submit, class:"btn btn-primary" %>
    </div>
    
  <% end %>
</div>

app/views/shortened_links/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Original Link:</strong>
    <%= @shortened_link.original_url %>
  </p>

  <p>
    <strong>Short Link:</strong>
    <%= request.base_url + '/s/' + @shortened_link.short_url_slug %>
  </p>

  <p>
    <strong>Visits:</strong>
    <%= @shortened_link.visit_count %>
  </p>

  <%= link_to 'Edit this Link', edit_shortened_link_path(@shortened_link) %> |
  <%= link_to 'Manage Links', shortened_links_path %>
</div>